### ISSUE TITLE
Using the action without a resource group

### ISSUE THREAD

**Issue by mustaphazorgati** [IBM/cloudfoundry-deploy#2]
Hey there!
I would love to use this action without the `default` resource group. Currently this is not possible, because you the resource group is hard wired.

Can we make it an optional parameter?

My current solution is copying all your steps and removing the `-g default`.

**Comment by mustaphazorgati** [comment]
Hey @filipecorrea,

what do you think about this issue? I am willing to create a PR. First I'd like to hear your thoughts tho so that my time is not "wasted" :)

**Comment by filipecorrea** [comment]
Hi @mustaphazorgati. Thanks for reaching out! I think it's a great idea to have an optional parameter that overrides the default resource group. I'm looking forward to your pull request!

**Comment by mustaphazorgati** [comment]
Hey @filipecorrea!
Thanks for your reply. Just a quick question: Should I allow to override the name of the default resource group and/or allow to disable the resource group completely?

**Comment by filipecorrea** [comment]
Good question. I think if it works without defining any resource group, we should remove it and allow it to be defined optionally. What do you say?

**Comment by mustaphazorgati** [comment]
Yes it does work without any resource group. That's my current workaround. The issue with that is that this action will have a breaking change if I remove the default behaviour.

**Comment by mustaphazorgati** [comment]
Is that acceptable?

**Comment by mustaphazorgati** [comment]
If downward compatibility is important I would create two optional input parameters: One to define a resource group, default: `default`. One to disable the resource group.

If downwards compatibility is not important I would create only one optional parameter to define a resource group. If this parameter is not defined the action will not use a resource group

**Comment by filipecorrea** [comment]
I think both solutions could be applied and I would appreciate if you could open 2 PRs then.

>If downward compatibility is important I would create two optional input parameters: One to define a resource group, default: default. One to disable the resource group.

This solution should be released as v1.x.

>If downwards compatibility is not important I would create only one optional parameter to define a resource group. If this parameter is not defined the action will not use a resource group

This solution will be released as v2.

**Comment by mustaphazorgati** [comment]
Will do over the weekend! Talk to you soon.

**Comment by mustaphazorgati** [comment]
Hey @filipecorrea!

I've created a total of 4 PRs. Two of them fix the issue as discussed, the other two are some quality of life changes.

* #3 adds descriptions for all existing parameters/inputs
* #4 allows location customization of the manifest file
* #5 is the backwards compatible solution (v1)
* #6 is the breaking solution (v2)

I couldn't test #5 and #6 properly yet. All I have done is testing it locally. That worked fine. I am expecting them to run fine. Further testing can be done after release.

TODOs:
- [ ] fix `Worflow Example` in README. That is still using the action with the master branch. 
- [ ] discuss how to handle both versions. Suggestion: branch for v1, master for v2
- [ ] reference v1 in README of v2 (if v2 is supposed to be the master branch)
- [ ] maybe mark v1 as deprecated or something of that sort?  

Hopefully this helps. :)

**Comment by mustaphazorgati** [comment]
Hey @filipecorrea!
I saw that you've merged #3, #4, and #5. Thanks! :)
Do you have any idea what to do with #6?

**Comment by filipecorrea** [comment]
Hi @mustaphazorgati. Steve and I are still figuring out how to publish those releases. #6 should be published soon as v2.

**Comment by mustaphazorgati** [comment]
Thanks for the information. If I can help somehow let me know :)

**Comment by mustaphazorgati** [comment]
Thank you for merging the PRs :)

Looking forward to work with you again in the future!

**Comment by filipecorrea** [comment]
Thanks for your contribution!

**Comment by mustaphazorgati** [comment]
hey @filipecorrea!

Just a small feedback from the user's perspective: The release notes don't mention anything. As a user I had to read through the README again and figure out what changed. I myself know what we've done, but other people might be annoyed by that. ;)

**Comment by filipecorrea** [comment]
Thanks, I updated release descriptions now.
