### ISSUE TITLE
Upgrade to latest IBM Cloud CLI

### ISSUE THREAD

**Issue by mustaphazorgati** [IBM/cloudfoundry-deploy#9]
I just received the following email regarding the deprecation of IBM Cloud CLI 1.X.X: 

![131543170-1155cab0-10bf-4427-971a-7c05a7de3985](https://user-images.githubusercontent.com/15628173/131544127-23b89489-1216-4b7b-87ac-b95a777e6309.png)

Does this affect this GitHub Action, or are we fine?

**Comment by mustaphazorgati** [comment]
Hey @filipecorrea,
october is just around the corner.. Can you have a look at this?

**Comment by filipecorrea** [comment]
Hi @mustaphazorgati. I didn't got that one, but I would assume the https://clis.cloud.ibm.com/install/linux won't be deprecated. Does the e-mail mention anything about this particular endpoint?

**Comment by mustaphazorgati** [comment]
Hey @filipecorrea,

unfortunately not. The E-Mail does not explicitly mention that endpoint. 
Suggestion: We wait til October, if this action breaks we fix it, if not, I'll close this ticket.
An alternative is to check the current version with `ibmcloud --version` and verify that we are using CLI 2.X.X

**Comment by mustaphazorgati** [comment]
Hey @filipecorrea,

everything seems fine. We are not affected.
